const std = @import("std");

// StarlingMonkey build (Zig 0.17 port of the CMake build).
//
// Toolchain: Zig 0.17 `zig cc`/`zig c++` targeting wasm32-wasi (reactor),
// replacing wasi-sdk. SpiderMonkey is built from source with the same Zig
// toolchain (the upstream prebuilt libspidermonkey.a is libc++-ABI-incompatible
// with Zig — see the zig17 conversion plan), producing a libc++ `__1` archive.

const Ctx = struct {
    b: *std.Build,
    cxx_flags: []const []const u8,
    c_flags: []const []const u8,
    common_includes: []const []const u8,
    builtins_incl_dir: std.Build.LazyPath,
    host_api_dir: []const u8,
    wasi020: []const u8,
    wasi023: []const u8,
};

pub fn build(b: *std.Build) void {
    const optimize = b.standardOptimizeOption(.{});

    // StarlingMonkey only targets wasm32-wasi (reactor).
    const target = b.resolveTargetQuery(.{ .cpu_arch = .wasm32, .os_tag = .wasi });

    const enable_debugger = b.option(bool, "debugger", "Enable JS debugger socket support") orelse true;
    const host_api_name = b.option([]const u8, "host-api", "Host API implementation under host-apis/") orelse "wasi-0.2.10";
    const use_wasm_opt = b.option(bool, "wasm-opt", "Optimize starling-raw.wasm with wasm-opt for release builds") orelse true;

    // SpiderMonkey artifacts built from source with Zig (see deps/mozconfig-zig).
    const sm_dist = b.option([]const u8, "spidermonkey-dist", "Path to the Zig-built SpiderMonkey dist dir") orelse "deps/sm-obj-zig/dist";
    const sm_confdefs = b.option([]const u8, "spidermonkey-confdefs", "Path to js-confdefs.h") orelse "deps/sm-obj-zig/js/src/js-confdefs.h";
    const sm_include = b.pathJoin(&.{ sm_dist, "include" });
    const sm_lib = b.pathJoin(&.{ sm_dist, "libspidermonkey.a" });

    const is_debug = optimize == .Debug;
    const gpa = b.allocator;

    // ---- Common compile flags (port of cmake/compile-flags.cmake) ----
    // Differences from the wasi-sdk build:
    //   * `-m32` dropped (wasm32 is already 32-bit; zig cc rejects it).
    //   * `-lwasi-emulated-*` link flags dropped; Zig's wasi-libc provides those
    //     symbols when the `-D_WASI_EMULATED_*` defines are set.
    const wasi_emulated = [_][]const u8{
        "-D_WASI_EMULATED_SIGNAL",
        "-D_WASI_EMULATED_PROCESS_CLOCKS",
        "-D_WASI_EMULATED_GETPID",
    };

    var cxx_flags: std.ArrayList([]const u8) = .empty;
    var c_flags: std.ArrayList([]const u8) = .empty;
    cxx_flags.appendSlice(gpa, &.{
        "-std=gnu++23",
        "-Wall",
        "-Wno-unknown-warning-option",
        "-Wno-invalid-offsetof",
        "-Wno-error=unused-result",
        "-Wimplicit-fallthrough",
        "-Qunused-arguments",
        "-fno-sized-deallocation",
        "-fno-aligned-new",
        "-mthread-model",
        "single",
        "-fPIC",
        "-fno-rtti",
        "-fno-exceptions",
        "-fno-math-errno",
        "-pipe",
        "-fno-omit-frame-pointer",
        "-funwind-tables",
        "-include",
        sm_confdefs,
    }) catch @panic("OOM");
    cxx_flags.appendSlice(gpa, &wasi_emulated) catch @panic("OOM");
    c_flags.appendSlice(gpa, &.{
        "-Wall",
        "-Wno-unknown-attributes",
        "-Wno-pointer-to-int-cast",
        "-Wno-int-to-pointer-cast",
    }) catch @panic("OOM");
    c_flags.appendSlice(gpa, &wasi_emulated) catch @panic("OOM");
    if (is_debug) cxx_flags.append(gpa, "-DDEBUG=1") catch @panic("OOM");
    if (enable_debugger) cxx_flags.append(gpa, "-DENABLE_JS_DEBUGGER") catch @panic("OOM");

    const common_includes = [_][]const u8{ "include", "deps/include", "runtime", sm_include };

    // ---- builtins.incl (port of cmake builtins.cmake NS_DEF generation) ----
    const builtins_incl =
        \\// Generated by build.zig
        \\NS_DEF(builtins::web::global_self)
        \\NS_DEF(builtins::web::queue_microtask)
        \\NS_DEF(builtins::web::structured_clone)
        \\NS_DEF(builtins::web::base64)
        \\NS_DEF(builtins::web::blob)
        \\NS_DEF(builtins::web::file)
        \\NS_DEF(builtins::web::event)
        \\NS_DEF(builtins::web::abort)
        \\NS_DEF(builtins::web::form_data)
        \\NS_DEF(builtins::web::dom_exception)
        \\NS_DEF(builtins::web::url)
        \\NS_DEF(builtins::web::console)
        \\NS_DEF(builtins::web::performance)
        \\NS_DEF(builtins::web::timers)
        \\NS_DEF(builtins::web::worker_location)
        \\NS_DEF(builtins::web::text_codec)
        \\NS_DEF(builtins::web::streams)
        \\NS_DEF(builtins::web::fetch)
        \\NS_DEF(builtins::web::fetch::fetch_event)
        \\NS_DEF(builtins::web::crypto)
        \\
    ;
    const wf = b.addWriteFiles();
    const builtins_incl_dir = wf.add("builtins.incl", builtins_incl).dirname();

    const ctx = Ctx{
        .b = b,
        .cxx_flags = cxx_flags.items,
        .c_flags = c_flags.items,
        .common_includes = &common_includes,
        .builtins_incl_dir = builtins_incl_dir,
        .host_api_dir = b.pathJoin(&.{ "host-apis", host_api_name }),
        .wasi020 = "host-apis/wasi-0.2.0",
        .wasi023 = "host-apis/wasi-0.2.3",
    };

    // ---- The final reactor executable ----
    // All StarlingMonkey C++ sources compile directly into the executable (not
    // archived), so the runtime's `export_name` entry points (wizer-initialize,
    // wizer.resume, cabi_realloc) are retained as GC roots and pull in the rest of
    // the program. Mirrors cmake `add_executable(starling-raw.wasm ${SOURCES})`.
    const link_mod = b.createModule(.{ .target = target, .optimize = optimize, .link_libc = true, .link_libcpp = true });
    const exe = b.addExecutable(.{ .name = "starling-raw", .root_module = link_mod });
    exe.wasi_exec_model = .reactor;
    // 1 MiB stack (cmake: -Wl,-z,stack-size=1048576). zig's wasm linker rejects
    // -Wl,--stack-first, so it is intentionally omitted.
    exe.stack_size = 1024 * 1024;
    addStarlingSources(ctx, link_mod);

    // Prebuilt component-type object for the selected host API.
    link_mod.addObjectFile(b.path(b.pathJoin(&.{ ctx.host_api_dir, "bindings/bindings_component_type.o" })));
    // OpenSSL libcrypto.a (cmake/openssl.cmake; linux-x32 installs to libx32/).
    link_mod.addObjectFile(b.path("deps/openssl-zig/libx32/libcrypto.a"));
    // Rust crate bundle (cmake/build-crates.cmake): encoding_mem_*, install_rust_hooks, url/multipart FFI.
    link_mod.addObjectFile(b.path("target/wasm32-wasip1/release/librust_staticlib.a"));
    // SpiderMonkey static lib (must be the Zig-built one; libc++ __1).
    link_mod.addObjectFile(b.path(sm_lib));

    // ---- Post-build: wasm-opt (port of the CMakeLists.txt USE_WASM_OPT block) ----
    var raw_wasm: std.Build.LazyPath = exe.getEmittedBin();
    if (use_wasm_opt and !is_debug) {
        if (b.lazyDependency("binaryen", .{})) |bin_dep| {
            const wo = std.Build.Step.Run.create(b, "wasm-opt");
            wo.addFileArg(bin_dep.path("binaryen-version_123/bin/wasm-opt"));
            wo.addArgs(&.{
                "--strip-debug",             "-O3",
                "--enable-bulk-memory",      "--enable-bulk-memory-opt",
                "--enable-sign-ext",         "--enable-mutable-globals",
                "--enable-nontrapping-float-to-int", "--enable-multivalue",
                "--enable-reference-types",  "--enable-extended-const",
            });
            wo.addArg("-o");
            const opt_out = wo.addOutputFileArg("starling-raw.wasm");
            wo.addFileArg(exe.getEmittedBin());
            raw_wasm = opt_out;
        }
    }
    const install_raw = b.addInstallBinFile(raw_wasm, "starling-raw.wasm");
    b.getInstallStep().dependOn(&install_raw.step);

    // ---- Componentization tooling (port of componentize.sh.in + adapter copy) ----
    // Install the preview1 adapter and a generated componentize.sh next to
    // starling-raw.wasm so the runtime can be turned into a component.
    const adapter = b.pathJoin(&.{ ctx.wasi020, if (is_debug) "preview1-adapter-debug" else "preview1-adapter-release", "wasi_snapshot_preview1.wasm" });
    b.getInstallStep().dependOn(&b.addInstallBinFile(b.path(adapter), "preview1-adapter.wasm").step);

    // componentize.sh references the tools via `$(dirname "$0")/…`, so install them
    // alongside it (relocatable, mirrors the CMake build directory layout).
    if (b.lazyDependency("wasm-tools", .{})) |d|
        b.getInstallStep().dependOn(&b.addInstallBinFile(d.path("wasm-tools-1.235.0-x86_64-linux/wasm-tools"), "wasm-tools").step);
    if (b.lazyDependency("wasmtime", .{})) |d|
        b.getInstallStep().dependOn(&b.addInstallBinFile(d.path("wasmtime-v42.0.1-x86_64-linux/wasmtime"), "wasmtime").step);
    if (b.lazyDependency("weval", .{})) |d|
        b.getInstallStep().dependOn(&b.addInstallBinFile(d.path("weval-v0.4.1-x86_64-linux/weval"), "weval").step);

    const componentize_sh = renderComponentizeScript(b);
    b.getInstallStep().dependOn(&b.addInstallBinFile(componentize_sh, "componentize.sh").step);

    // `zig build smoke-test`: componentize a trivial script and validate the
    // resulting component. Runs the *installed* componentize.sh so it finds
    // starling-raw.wasm, the adapter and the tools next to itself. (The full
    // multi-module e2e smoke.js needs the test harness's --strip-path-prefix and
    // is covered by the ported test suite, not this build step.)
    const smoke = b.step("smoke-test", "Componentize a trivial script and validate the component");
    const smoke_js = b.addWriteFiles().add("smoke.js", "addEventListener('fetch', e => e.respondWith(new Response('ok')));\nconsole.log('smoke ok');\n");
    b.getInstallStep().dependOn(&b.addInstallBinFile(smoke_js, "smoke.js").step);
    const smoke_out = b.getInstallPath(.bin, "smoke.wasm");
    const smoke_run = std.Build.Step.Run.create(b, "componentize smoke");
    smoke_run.addArgs(&.{ "bash", b.getInstallPath(.bin, "componentize.sh"), b.getInstallPath(.bin, "smoke.js"), "-o", smoke_out });
    smoke_run.step.dependOn(b.getInstallStep());
    if (b.lazyDependency("wasm-tools", .{})) |d| {
        const validate = std.Build.Step.Run.create(b, "validate smoke component");
        validate.addFileArg(d.path("wasm-tools-1.235.0-x86_64-linux/wasm-tools"));
        validate.addArgs(&.{ "validate", "--features", "all", smoke_out });
        validate.step.dependOn(&smoke_run.step);
        smoke.dependOn(&validate.step);
    }

    // ---- Objects-only verification step ----
    // A static archive that compiles the full C++ tree without resolving the
    // SpiderMonkey/Rust/OpenSSL externals.
    const cc_mod = b.createModule(.{ .target = target, .optimize = optimize, .link_libc = true, .link_libcpp = true });
    const cc_lib = b.addLibrary(.{ .name = "starling_cc", .root_module = cc_mod, .linkage = .static });
    addStarlingSources(ctx, cc_mod);
    const cc_step = b.step("cc", "Compile the StarlingMonkey C++ sources (objects only)");
    cc_step.dependOn(&cc_lib.step);
}

// Render componentize.sh from componentize.sh.in, pointing the tool paths at the
// binaries installed next to it (resolved at runtime via `$(dirname "$0")`).
fn renderComponentizeScript(b: *std.Build) std.Build.LazyPath {
    const template = @embedFile("componentize.sh.in");
    var buf = std.ArrayList(u8).empty;
    const gpa = b.allocator;
    var rest: []const u8 = template;
    const subs = [_]struct { from: []const u8, to: []const u8 }{
        .{ .from = "@WASMTIME_DIR@", .to = "$(dirname \"$0\")" },
        .{ .from = "@WASM_TOOLS_BIN@", .to = "$(dirname \"$0\")/wasm-tools" },
        .{ .from = "@WEVAL_BIN@", .to = "$(dirname \"$0\")/weval" },
        .{ .from = "@AOT@", .to = "0" },
    };
    outer: while (rest.len != 0) {
        for (subs) |s| {
            if (std.mem.startsWith(u8, rest, s.from)) {
                buf.appendSlice(gpa, s.to) catch @panic("OOM");
                rest = rest[s.from.len..];
                continue :outer;
            }
        }
        buf.append(gpa, rest[0]) catch @panic("OOM");
        rest = rest[1..];
    }
    const wf = b.addWriteFiles();
    return wf.add("componentize.sh", buf.items);
}

fn addStarlingSources(ctx: Ctx, mod: *std.Build.Module) void {
    const b = ctx.b;
    for (ctx.common_includes) |d| mod.addIncludePath(b.path(d));
    mod.addIncludePath(ctx.builtins_incl_dir);
    mod.addIncludePath(b.path("crates/rust-url"));
    mod.addIncludePath(b.path("crates/rust-multipart"));
    mod.addIncludePath(b.path("deps/openssl-zig/include"));

    // runtime sources (cmake top-level SOURCES).
    mod.addCSourceFiles(.{ .files = &runtime_sources, .flags = ctx.cxx_flags, .language = .cpp });
    // builtins install dispatcher + all default-enabled builtins.
    mod.addCSourceFile(.{ .file = b.path("builtins/install_builtins.cpp"), .flags = ctx.cxx_flags, .language = .cpp });
    mod.addCSourceFiles(.{ .files = &builtin_sources, .flags = ctx.cxx_flags, .language = .cpp });

    // rust-hooks C++ support file (cmake target rust-hooks-wrappers): provides RustMozCrash.
    mod.addCSourceFile(.{ .file = b.path("crates/rust-hooks/src/wrappers.cpp"), .flags = ctx.cxx_flags, .language = .cpp });

    // host_api (port of host-apis/<name>/host_api.cmake for wasi-0.2.x).
    mod.addIncludePath(b.path(b.pathJoin(&.{ ctx.wasi020, "include" })));
    mod.addIncludePath(b.path(b.pathJoin(&.{ ctx.wasi023, "include" })));
    mod.addIncludePath(b.path(ctx.wasi020));
    mod.addIncludePath(b.path(b.pathJoin(&.{ ctx.host_api_dir, "include" })));
    mod.addCSourceFiles(.{ .files = &.{
        b.pathJoin(&.{ ctx.wasi020, "host_api.cpp" }),
        b.pathJoin(&.{ ctx.wasi020, "host_call.cpp" }),
        b.pathJoin(&.{ ctx.wasi023, "sockets.cpp" }),
    }, .flags = ctx.cxx_flags, .language = .cpp });
    mod.addCSourceFile(.{ .file = b.path(b.pathJoin(&.{ ctx.host_api_dir, "bindings/bindings.c" })), .flags = ctx.c_flags, .language = .c });
}

const runtime_sources = [_][]const u8{
    "runtime/js.cpp",
    "runtime/allocator.cpp",
    "runtime/encode.cpp",
    "runtime/decode.cpp",
    "runtime/engine.cpp",
    "runtime/event_loop.cpp",
    "runtime/builtin.cpp",
    "runtime/script_loader.cpp",
    "runtime/debugger.cpp",
};

const builtin_sources = [_][]const u8{
    "builtins/web/global_self.cpp",
    "builtins/web/queue-microtask.cpp",
    "builtins/web/structured-clone.cpp",
    "builtins/web/base64.cpp",
    "builtins/web/blob.cpp",
    "builtins/web/file.cpp",
    "builtins/web/console.cpp",
    "builtins/web/performance.cpp",
    "builtins/web/worker-location.cpp",
    "builtins/web/dom-exception.cpp",
    "builtins/web/url.cpp",
    "builtins/web/timers.cpp",
    "builtins/web/event/event.cpp",
    "builtins/web/event/event-target.cpp",
    "builtins/web/event/custom-event.cpp",
    "builtins/web/event/global-event-target.cpp",
    "builtins/web/abort/abort-signal.cpp",
    "builtins/web/abort/abort-controller.cpp",
    "builtins/web/form-data/form-data.cpp",
    "builtins/web/form-data/form-data-encoder.cpp",
    "builtins/web/form-data/form-data-parser.cpp",
    "builtins/web/text-codec/text-codec.cpp",
    "builtins/web/text-codec/text-decoder.cpp",
    "builtins/web/text-codec/text-encoder.cpp",
    "builtins/web/streams/buf-reader.cpp",
    "builtins/web/streams/compression-stream.cpp",
    "builtins/web/streams/decompression-stream.cpp",
    "builtins/web/streams/native-stream-sink.cpp",
    "builtins/web/streams/native-stream-source.cpp",
    "builtins/web/streams/streams.cpp",
    "builtins/web/streams/transform-stream.cpp",
    "builtins/web/streams/transform-stream-default-controller.cpp",
    "builtins/web/fetch/fetch-api.cpp",
    "builtins/web/fetch/fetch-utils.cpp",
    "builtins/web/fetch/headers.cpp",
    "builtins/web/fetch/request-response.cpp",
    "builtins/web/fetch/fetch_event.cpp",
    "builtins/web/crypto/crypto.cpp",
    "builtins/web/crypto/crypto-algorithm.cpp",
    "builtins/web/crypto/crypto-key.cpp",
    "builtins/web/crypto/crypto-key-ec-components.cpp",
    "builtins/web/crypto/crypto-key-rsa-components.cpp",
    "builtins/web/crypto/json-web-key.cpp",
    "builtins/web/crypto/subtle-crypto.cpp",
    "builtins/web/crypto/uuid.cpp",
};
