#!/usr/bin/env python3
"""Generate a full WIT closure for a Phase 0 compat fixture, suitable for
`zig build -Dcomponent-wit=... -Dcomponent-world=js-dispatch
-Ddispatch-wit=... -Ddispatch-world=js-exports` (see README.md /
host-apis/wasi-0.2.10/wit/js-dispatch.wit).

Each fixture under tests/compat/fixtures/<id>/wit/world.wit declares its
exports directly on a `world js-exports { export foo: func(...); ... }`
(see manifest.json known_deviations "interface-export-flattening" for why).
To build the *real* runtime/js_dispatch.cpp+.zig bridge against that surface,
this script rewrites the fixture's world body into an `interface api { ... }`
(stripping the per-function `export` keyword, which is a world-level-only
qualifier and invalid inside an interface) and splices it into a copy of
host-apis/wasi-0.2.10/wit -- the WIT closure that host-apis/wasi-0.2.10/
wit/js-dispatch.wit's `js-dispatch` world already imports the full WASI
surface for and exports `starling:js/api` from -- replacing that closure's
own deps/starling-js/package.wit (whose `add`/`greet`/... functions are
tests/fixtures/js-dispatch.js's, not any compat fixture's).

This is a build-time code generation step: it does not modify or replace
the original, independently-authored fixtures themselves (tests/compat/
fixtures/<id>/wit/world.wit, component.js) which remain the single source
of truth; it only re-expresses the same declarations in the interface shape
the full WASI-importing world requires.
"""
import re
import shutil
import sys
from pathlib import Path

_EXPORT_FN_RE = re.compile(r"^(?P<indent>[ \t]*)export(?P<rest>\s+[A-Za-z0-9_-]+\s*:\s*func\b.*)$")


def _extract_world_body(wit_text: str, world_name: str = "js-exports") -> str:
    """Return the text between the outermost `{` and matching `}` of
    `world <world_name> { ... }` in wit_text, preserving interior
    whitespace/comments/records verbatim."""
    marker = f"world {world_name}"
    start = wit_text.find(marker)
    if start == -1:
        raise ValueError(f"no `{marker}` world found")
    brace_open = wit_text.index("{", start)
    depth = 0
    for i in range(brace_open, len(wit_text)):
        if wit_text[i] == "{":
            depth += 1
        elif wit_text[i] == "}":
            depth -= 1
            if depth == 0:
                return wit_text[brace_open + 1 : i]
    raise ValueError(f"unbalanced braces in `{marker}` world")


def _strip_export_keyword(body: str) -> str:
    """Interfaces (unlike worlds) declare functions without a leading
    `export` keyword; strip it line-by-line so `export foo: func(...)`
    becomes `foo: func(...)` while leaving everything else (records,
    comments, blank lines) untouched."""
    out_lines = []
    for line in body.splitlines():
        m = _EXPORT_FN_RE.match(line)
        if m:
            out_lines.append(f"{m.group('indent')}{m.group('rest').lstrip()}")
        else:
            out_lines.append(line)
    return "\n".join(out_lines)


def render_package_wit(fixture_world_wit: Path) -> str:
    wit_text = fixture_world_wit.read_text()
    body = _strip_export_keyword(_extract_world_body(wit_text))
    return (
        "// Generated by tests/compat/lib/gen_bridge_wit.py from\n"
        f"// {fixture_world_wit} -- do not edit directly.\n"
        "package starling:js;\n\n"
        "interface api {\n"
        f"{body}\n"
        "}\n\n"
        "world js-exports {\n"
        "  export api;\n"
        "}\n"
    )


def generate(base_wit_dir: Path, fixture_wit_dir: Path, out_dir: Path) -> tuple[Path, Path]:
    """Copy base_wit_dir (the full WASI-importing closure) to out_dir, then
    overwrite its deps/starling-js/package.wit with one derived from
    fixture_wit_dir/world.wit. Returns (component_wit_dir, dispatch_wit_dir)."""
    if out_dir.exists():
        shutil.rmtree(out_dir)
    shutil.copytree(base_wit_dir, out_dir)
    dispatch_wit_dir = out_dir / "deps" / "starling-js"
    package_wit = dispatch_wit_dir / "package.wit"
    if not package_wit.exists():
        raise FileNotFoundError(f"expected {package_wit} after copying {base_wit_dir}")
    package_wit.write_text(render_package_wit(fixture_wit_dir / "world.wit"))
    return out_dir, dispatch_wit_dir


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(
            "usage: gen_bridge_wit.py <base-wit-dir> <fixture-wit-dir> <out-dir>",
            file=sys.stderr,
        )
        return 2
    base_wit_dir, fixture_wit_dir, out_dir = (Path(a) for a in argv[1:])
    component_wit, dispatch_wit = generate(base_wit_dir, fixture_wit_dir, out_dir)
    print(component_wit)
    print(dispatch_wit)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
